### ISSUE TITLE
Docx not parsing after conversion to exe via cx_freeze

### ISSUE THREAD

**Issue by Pika-Boo** [deanmalmgren/textract#142] opened 2017-03-27 17:42 UTC
I converted my code which simply parses and prints a docx file. However post conversion to exe via cx_freeze(After addition of the packages) getting the following error:
![image](https://cloud.githubusercontent.com/assets/7687847/24369818/d87bf068-1342-11e7-9acd-015546f4f582.png)

**Comment by deanmalmgren** [comment] 2017-03-28 11:17
I'm sorry to see you ran into trouble. 

This sounds like an issue with cx_freeze. textract does not import all parsers directly from `textract.parsers.__init__.py`, which apparently [causes issues with how cx_freeze detects dependencies and copies files over](https://cx-freeze.readthedocs.io/en/latest/faq.html#problems-with-running-frozen-programs). I'm going to close this issue, but please let me know if tgia is not the root cause of the issue.

**Closed by deanmalmgren** 2017-03-28 11:17 UTC

**Comment by Pika-Boo** [comment] 2017-03-29 09:06
Two quick follow ups then:
1) Does textract install all its package dependencies 
2) Can I find a list of dependencies which I could probably import while using cxFreeze so that textract continues to work

**Comment by deanmalmgren** [comment] 2017-03-29 10:42
It does install all of its dependencies. Those are specified [here](https://github.com/deanmalmgren/textract/blob/master/requirements/python) but please note that textract also uses [system packages](http://textract.readthedocs.io/en/stable/installation.html)
