### ISSUE TITLE
Use portable apps

### ISSUE THREAD

**Issue by Gerlo5** [deanmalmgren/textract#105] opened 2016-02-20 21:16 UTC
Hi,
I've WinPython in my USB key to use it at work, and I would like to use textract on .docs.
I've read that it requires Antiword, and I've it in the key.
Is there a way to use portable apps, like Antiword in this case, with textract?

**Comment by Gerlo5** [comment] 2016-02-21 13:27
I solved it in an ugly way: i changed the doc_parser to adapt it to my environment:
`    def extract(self, filename, **kwargs):'
'	import os'
'        dir=os.getcwd()'
'        os.putenv('ANTIWORDHOME', dir[0]+':/WinPython/tools/antiword/')'
'        stdout, stderr = self.run(dir[0]+':/WinPython/tools/antiword/antiword "%(filename)s" -m 8859-15' % locals())`
Is there a better way?

**Comment by deanmalmgren** [comment] 2016-02-22 15:12
The issue is that `antiword` must not be on your `PATH`, or at least that's what the issue would be in a UNIX environment. I'm not sure what the equivalent is in a WinPython environment. Basically, your shell interpreter can't find `antiword`.

The documentation for running textract in a windows environment is woefully inadequate. If you come up with a reliable way of installing antiword and the other textract dependencies, it would be really awesome if you could contribute your advice and guidance as a pull request. There are [basic instructions for adding new operating system installation instructions](https://github.com/deanmalmgren/textract/blob/master/docs/installation.rst#dont-see-your-operating-system-installation-instructions-here), but even throwing something in this or another github issue would be great so other people can use textract in windows environments as well.

I'm going to close this issue and #106 in the meantime, but I'll try and keep an eye on these things and help out where I can if you have follow-up questions to either of these issues.

**Closed by deanmalmgren** 2016-02-22 15:12 UTC
