### ISSUE TITLE
Hi everyone, cant install textract to jupyter, Anaconda, Windows 10

### ISSUE THREAD

**Issue by MekeSakensky** [deanmalmgren/textract#301] opened 2019-09-01 23:54 UTC
Any help highly appreciated,
urgently need something efficient for my ongoing project. Textract or any library to extract text from PDF and MS Word   thank in advance.

**Comment by MekeSakensky** [comment] 2019-09-01 23:58
THere are still no installation instructions for Windows 10 on official website https://textract.readthedocs.io/en/stable/

**Comment by yeshanliu** [comment] 2019-09-02 02:54
try 'pip install textract'

**Comment by MekeSakensky** [comment] 2019-09-02 03:02
tried, doesnt work

**Comment by MekeSakensky** [comment] 2019-09-02 03:12
![image](https://user-images.githubusercontent.com/48585802/64088110-bf81fe00-cd61-11e9-9969-d5b05f9b36fd.png)

**Comment by MekeSakensky** [comment] 2019-09-02 03:13
![image](https://user-images.githubusercontent.com/48585802/64088124-d9234580-cd61-11e9-898e-dadc80b45c6c.png)

**Comment by jpweytjens** [comment] 2019-09-02 08:08
@MekeSakensky 
The issue is "Read timed out" while downloading one of the textract dependencies. Can you try installing again? The issue is related to your internet connection or the server, not textract.

**Comment by MekeSakensky** [comment] 2019-09-02 14:14
Thank you very much, after several attempts it is much better but still throws following error:
![image](https://user-images.githubusercontent.com/48585802/64120539-45339700-cdbe-11e9-9499-d2a91c062dc2.png)

**Comment by MekeSakensky** [comment] 2019-09-02 14:15
what to do with it?

**Comment by yeshanliu** [comment] 2019-09-02 14:36
Manually delete old ‘olefile’ folder in Anaconda, then reinstall textract

**Comment by MekeSakensky** [comment] 2019-09-02 15:48
Unfortunately not working

**Comment by MekeSakensky** [comment] 2019-09-02 15:48
![image](https://user-images.githubusercontent.com/48585802/64125331-6d75c280-cdcb-11e9-8a85-ed52d5b35a45.png)

**Comment by MekeSakensky** [comment] 2019-09-02 16:01
I deleted all 'olefile' files and folders because I dont know what stands for "delete OLD olefile folder"
see below, but it is still throwingg the same error:
![image](https://user-images.githubusercontent.com/48585802/64125804-28529000-cdcd-11e9-8d60-00cdb2686c88.png)

**Comment by yeshanliu** [comment] 2019-09-03 01:11
What about olefile.egg-info ? This file also needs to be deleted，then try reinstall textract.

**Comment by jpweytjens** [comment] 2019-09-03 07:38
You should delete any file that is related in `C:\programdata\anaconda3\lib\site-packages` that is related to `OleFile`. After deleting those files, installation should work.

**Comment by MekeSakensky** [comment] 2019-09-03 14:21
Thank you very much guys, it worked.

**Comment by MekeSakensky** [comment] 2019-09-03 14:25
Have two more questions:
1. Can you tell more about fundamental things, like how to resolve such kind installation problems
2. Could help me with installation of Annoy package (creator of Annoy package couldn't resolve my problem). Anaconda Prompt throws following error(s):
![image](https://user-images.githubusercontent.com/48585802/64181795-f868c280-ce88-11e9-92d2-7e87dd2940ef.png)

**Comment by jpweytjens** [comment] 2019-09-04 08:18
The error message and its solution are very clear. `Microsoft visual C++ 14.0 is required. Get with with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools`

I would recommend reading the error messages as they very often tell you what the problem is. In this case, it even tells you how to solve it. With more cryptic error messages, googling them usually leads to some related topic on sites such as [StackOverflow](https://stackoverflow.com/). If you go through these posts, you usually learn quickly by reading, trying and experimenting.

Closing this topic as the issue is not related to textract anymore. I hope the above suggestions help you on your way.

**Closed by jpweytjens** 2019-09-04 08:18 UTC
